name: game_app
description: "讓子彈飛 X 甄嬛傳 台詞接龍王"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/new/
    - assets/audio/click.mp3
    - assets/audio/correct.mp3
    - assets/images/gameboy.jpg

  fonts:
    - family: NotoSerifTC
      fonts:
        - asset: assets/NotoSerifTC-Regular.ttf
